canton {
  parameters {
    non-standard-config = yes
  }
  participants {
    sandbox {
      ledger-api {
        auth-services = [{
          type = unsafe-jwt-hmac-256
          secret = "super-secret-dev-key-replace-in-production"
        }]
      }
    }
  }
}
