/**
 * @file validators.ts
 * @description Zod validation schemas for all synCCap REST API request payloads.
 *
 * Design Rationale:
 * -----------------
 * All numeric Daml fields (Numeric type) are validated as **string** inputs
 * and converted to strings for the @daml/types library. This avoids IEEE 754
 * floating-point precision loss when handling financial values like
 * costBasisPerWafer ($18,500.00) or penaltyRate (0.25).
 *
 * The Daml codegen represents `Numeric` as a string internally, so string
 * input maps directly to the wire format without lossy conversion.
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Shared Primitives
// ---------------------------------------------------------------------------

/**
 * Valid semiconductor technology nodes matching the Daml `TechnologyNode` enum.
 * Must exactly match the string union generated by `daml codegen js`.
 */
export const TechnologyNodeSchema = z.enum(['N3nm', 'N5nm', 'N7nm', 'N14nm'], {
  message: 'technologyNode must be one of: N3nm, N5nm, N7nm, N14nm',
});

/**
 * A positive decimal value represented as a string.
 * Validates that the string is a valid number and is strictly positive.
 *
 * Canton/Daml note: The @daml/types `Numeric` type serialises as a string
 * to preserve arbitrary precision. We validate the format here and pass
 * the string directly to the Daml ledger client.
 */
const positiveDecimalString = z
  .string()
  .regex(
    /^\d+(\.\d+)?$/,
    'Must be a positive decimal number as a string (e.g., "18500.00")'
  )
  .refine(
    (val) => parseFloat(val) > 0,
    'Value must be strictly greater than zero'
  );

/**
 * A non-empty Daml contract ID.
 * Contract IDs are opaque strings issued by the Canton participant node.
 */
const contractIdString = z
  .string()
  .min(1, 'contractId must be a non-empty string');

/**
 * A Daml party identifier.
 * In the sandbox, these are simple display names (e.g., "TSMC", "AppleInc").
 * In production Canton, they are participant-scoped party IDs.
 */
const partyString = z
  .string()
  .min(1, 'Party identifier must be a non-empty string');

/**
 * An ISO-8601 date string for capacity commitment periods.
 * We accept a loose format (YYYY-MM-DD) rather than full ISO to keep
 * the hackathon demo simple.
 */
const dateString = z
  .string()
  .min(1, 'Date must be a non-empty string (e.g., "2025-07-01")');

// ---------------------------------------------------------------------------
// Request Body Schemas
// ---------------------------------------------------------------------------

/**
 * Schema for POST /api/v1/assets — Create a new CapacityAsset.
 *
 * Canton note: Creating a CapacityAsset requires dual authorization from
 * both `manufacturer` and `owner`. In the sandbox, the authenticated party
 * submits via `submitMulti` with both parties listed in `actAs`. In production,
 * this would be a multi-party submission workflow.
 */
export const CreateAssetSchema = z.object({
  /** The foundry party that issues the capacity commitment. */
  manufacturer: partyString,
  /** The initial owner (primary buyer) of the capacity token. */
  owner: partyString,
  /** Unique lot identifier (e.g., "LOT-TSMC-3NM-2025Q3-001"). */
  assetId: z.string().min(1, 'assetId must be a non-empty string'),
  /** Semiconductor process node. */
  technologyNode: TechnologyNodeSchema,
  /** Monthly wafer allocation. */
  waferStartsPerMonth: z
    .number()
    .int('waferStartsPerMonth must be an integer')
    .positive('waferStartsPerMonth must be positive'),
  /** Price per wafer paid by the owner (PRIVACY-CRITICAL). */
  costBasisPerWafer: positiveDecimalString,
  /** Commitment period start. */
  commitmentStartDate: dateString,
  /** Commitment period end. */
  commitmentEndDate: dateString,
});
export type CreateAssetRequest = z.infer<typeof CreateAssetSchema>;

/**
 * Schema for POST /api/v1/transfers/propose — Initiate a dark pool RFQ.
 *
 * Canton note: This exercises the `ProposeTransfer` choice on a CapacityAsset,
 * which atomically archives the asset and creates a TransferRFQ. The secondary
 * buyer is added as an observer and can see the asking price but NOT the
 * original costBasisPerWafer.
 */
export const ProposeTransferSchema = z.object({
  /** Contract ID of the CapacityAsset to offer for sale. */
  assetContractId: contractIdString,
  /** The prospective buyer party. */
  secondaryBuyer: partyString,
  /** Asking price per wafer (visible to the buyer). */
  askingPricePerWafer: positiveDecimalString,
});
export type ProposeTransferRequest = z.infer<typeof ProposeTransferSchema>;

/**
 * Schema for POST /api/v1/transfers/accept — Accept a TransferRFQ (atomic settlement).
 *
 * Canton note: This exercises `AcceptTransfer` on a TransferRFQ, atomically
 * archiving the RFQ and creating a new CapacityAsset with the buyer as owner.
 * The new asset's costBasisPerWafer is set to agreedPricePerWafer — the
 * original seller's cost is permanently severed.
 */
export const AcceptTransferSchema = z.object({
  /** Contract ID of the TransferRFQ to accept. */
  rfqContractId: contractIdString,
  /** The negotiated price per wafer. */
  agreedPricePerWafer: positiveDecimalString,
});
export type AcceptTransferRequest = z.infer<typeof AcceptTransferSchema>;

/**
 * Schema for POST /api/v1/penalties/initiate — Trigger penalty workflow.
 *
 * Canton note: This exercises `InitiatePenalty` on a CapacityAsset,
 * creating a PenaltyAgreement visible ONLY to the manufacturer and
 * penalized party. No other network participant can detect the cancellation.
 */
export const InitiatePenaltySchema = z.object({
  /** Contract ID of the CapacityAsset being canceled. */
  assetContractId: contractIdString,
  /** Penalty rate as a decimal between 0 (exclusive) and 1 (inclusive). */
  penaltyRate: positiveDecimalString.refine(
    (val) => parseFloat(val) <= 1,
    'penaltyRate must be between 0 (exclusive) and 1 (inclusive)'
  ),
  /** Human-readable reason for the cancellation. */
  cancellationReason: z
    .string()
    .min(1, 'cancellationReason must be a non-empty string'),
});
export type InitiatePenaltyRequest = z.infer<typeof InitiatePenaltySchema>;

/**
 * Schema for POST /api/v1/penalties/settle — Confirm penalty payment.
 *
 * Canton note: This exercises `SettlePenalty` on a PenaltyAgreement.
 * Only the manufacturer can exercise this choice, confirming they
 * received the penalty payment.
 */
export const SettlePenaltySchema = z.object({
  /** Contract ID of the PenaltyAgreement to settle. */
  penaltyContractId: contractIdString,
});
export type SettlePenaltyRequest = z.infer<typeof SettlePenaltySchema>;

/**
 * Schema for POST /auth/token — Issue a sandbox development token.
 *
 * ⚠️ SANDBOX ONLY. In production, tokens are issued by the participant
 * node's IAM / Identity Provider.
 */
export const IssueTokenSchema = z.object({
  /** The Daml party display name to issue a token for. */
  party: partyString,
  /** Optional additional parties this token can read on behalf of. */
  readAs: z.array(partyString).optional(),
});
export type IssueTokenRequest = z.infer<typeof IssueTokenSchema>;
