/**
 * @file validators.ts
 * @description Zod validation schemas for all synCCap REST API request payloads.
 *
 * Design Rationale:
 * -----------------
 * All numeric Daml fields (Numeric type) are validated as **string** inputs
 * and converted to strings for the @daml/types library. This avoids IEEE 754
 * floating-point precision loss when handling financial values like
 * costBasisPerWafer ($18,500.00) or penaltyRate (0.25).
 *
 * The Daml codegen represents `Numeric` as a string internally, so string
 * input maps directly to the wire format without lossy conversion.
 */

import { z } from '@hono/zod-openapi';

// ---------------------------------------------------------------------------
// Shared Primitives
// ---------------------------------------------------------------------------

/**
 * Valid semiconductor technology nodes matching the Daml `TechnologyNode` enum.
 * Must exactly match the string union generated by `daml codegen js`.
 */
export const TechnologyNodeSchema = z.enum(['N3nm', 'N5nm', 'N7nm', 'N14nm'], {
  message: 'technologyNode must be one of: N3nm, N5nm, N7nm, N14nm',
}).openapi({
  description: 'Semiconductor technology node',
  example: 'N3nm',
});

/**
 * A positive decimal value represented as a string.
 */
const positiveDecimalString = z
  .string()
  .regex(
    /^\d+(\.\d+)?$/,
    'Must be a positive decimal number as a string (e.g., "18500.00")'
  )
  .refine(
    (val) => parseFloat(val) > 0,
    'Value must be strictly greater than zero'
  );

/**
 * A non-empty Daml contract ID.
 */
const contractIdString = z
  .string()
  .min(1, 'contractId must be a non-empty string');

/**
 * A Daml party identifier.
 */
const partyString = z
  .string()
  .min(1, 'Party identifier must be a non-empty string');

/**
 * An ISO-8601 date string for capacity commitment periods.
 */
const dateString = z
  .string()
  .min(1, 'Date must be a non-empty string (e.g., "2025-07-01")');

// ---------------------------------------------------------------------------
// Request Body Schemas
// ---------------------------------------------------------------------------

export const CreateAssetSchema = z.object({
  owner: partyString.openapi({ example: 'AppleInc' }),
  assetId: z.string().min(1).openapi({ example: 'LOT-TSMC-3NM-2025Q3-001' }),
  technologyNode: TechnologyNodeSchema,
  waferStartsPerMonth: z.number().int().positive().openapi({ example: 200 }),
  costBasisPerWafer: positiveDecimalString.openapi({ example: '18500.00' }),
  commitmentStartDate: dateString.openapi({ example: '2025-07-01' }),
  commitmentEndDate: dateString.openapi({ example: '2026-06-30' }),
}).openapi('CreateAssetRequest');
export type CreateAssetRequest = z.infer<typeof CreateAssetSchema>;

export const ProposeTransferSchema = z.object({
  assetContractId: contractIdString.openapi({ example: '00abcd...' }),
  secondaryBuyer: partyString.openapi({ example: 'QualcommInc' }),
  askingPricePerWafer: positiveDecimalString.openapi({ example: '21500.00' }),
}).openapi('ProposeTransferRequest');
export type ProposeTransferRequest = z.infer<typeof ProposeTransferSchema>;

export const AcceptTransferSchema = z.object({
  rfqContractId: contractIdString.openapi({ example: '00efgh...' }),
  agreedPricePerWafer: positiveDecimalString.openapi({ example: '21500.00' }),
}).openapi('AcceptTransferRequest');
export type AcceptTransferRequest = z.infer<typeof AcceptTransferSchema>;

export const InitiatePenaltySchema = z.object({
  assetContractId: contractIdString.openapi({ example: '00abcd...' }),
  penaltyRate: positiveDecimalString.refine(
    (val) => parseFloat(val) <= 1,
    'penaltyRate must be between 0 (exclusive) and 1 (inclusive)'
  ).openapi({ example: '0.25' }),
  cancellationReason: z.string().min(1).openapi({ example: 'Order cancellation due to supply chain issues' }),
}).openapi('InitiatePenaltyRequest');
export type InitiatePenaltyRequest = z.infer<typeof InitiatePenaltySchema>;

export const SettlePenaltySchema = z.object({
  penaltyContractId: contractIdString.openapi({ example: '00xyz...' }),
}).openapi('SettlePenaltyRequest');
export type SettlePenaltyRequest = z.infer<typeof SettlePenaltySchema>;

export const IssueTokenSchema = z.object({
  party: partyString.openapi({ example: 'TSMC' }),
  additionalActAs: z.array(partyString).optional().openapi({ example: ['AppleInc'] }),
  readAs: z.array(partyString).optional().openapi({ example: ['AppleInc'] }),
}).openapi('IssueTokenRequest');
export type IssueTokenRequest = z.infer<typeof IssueTokenSchema>;

